/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/original/abandoned_warehouse_-_interior_scene.glb --transform 
Files: public/original/abandoned_warehouse_-_interior_scene.glb [114.8MB] > C:\Users\jova1\Documents\ar-arch-edu\abandoned_warehouse_-_interior_scene-transformed.glb [5.15MB] (96%)
Author: Aurélien Martel (https://sketchfab.com/aurelien_martel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abandoned-warehouse-interior-scene-1d5285f2e0fd4211a27c8042496d5959
Title: Abandoned Warehouse - Interior Scene
*/

import { useGLTF } from "@react-three/drei";
import { MallaInteractiva } from "./MallaInteractiva";

export function AbandonedWarehouseInteriorScene(props) {
  const { nodes, materials } = useGLTF("./models/abandoned_warehouse_-_interior_scene-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <MallaInteractiva
        geometry={nodes.TexturesCom_WindowsBacklit0019_13_M_0.geometry}
        material={materials["fenetre.006"]}
        position={[14.282, 0.412, -0.052]}
        scale={3.51}
        info={{
          titulo: "Fenetre",
          texto: "Capa de fenetre.",
        }}
      />
      <mesh
        geometry={nodes.TexturesCom_WindowsBacklit0019_14_M_0.geometry}
        material={materials["fenetre.005"]}
        position={[9.741, 0.412, -0.052]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.TexturesCom_WindowsBacklit0019_15_M_0.geometry}
        material={materials["fenetre.002"]}
        position={[4.914, 0.412, -0.052]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.TexturesCom_WindowsBacklit0019_12_M_0.geometry}
        material={materials["fenetre.004"]}
        position={[-0.011, 0.412, -0.052]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Cube_0.geometry}
        material={materials["briques-ss-fenetre"]}
        position={[0, -2.159, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Cube002_0.geometry}
        material={materials["briques-sur-fenetre"]}
        position={[-0.34, 2.981, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Cube001_0.geometry}
        material={materials["colonne-beton"]}
        position={[-2.653, -0.717, -0.193]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Plane_0.geometry}
        material={materials.material}
        position={[0, -2.933, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={35.097}
      />
      <mesh geometry={nodes.Plane002_0.geometry} material={materials["mur-gauche"]} position={[0.677, -0.242, -10.079]} scale={3.51} />
      <mesh
        geometry={nodes.Plane003_0.geometry}
        material={materials["mur-fond"]}
        position={[16.878, 3.268, -3.344]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Plane004_0.geometry}
        material={materials["mur-arriere"]}
        position={[-12.211, 3.268, -3.344]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={3.51}
      />
      <mesh geometry={nodes.Plane005_0.geometry} material={materials["mur-droite"]} position={[-7.514, 0.046, 0.131]} scale={3.51} />
      <mesh
        geometry={nodes.Cube003_0.geometry}
        material={materials["colonne-beton.001"]}
        position={[-2.653, -0.717, -9.709]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Cube004_0.geometry}
        material={materials["poutre-toit.001"]}
        position={[16.696, 2.667, -5.122]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Plane001_0.geometry}
        material={materials["toiture-tole"]}
        position={[16.693, 3.758, -5.121]}
        rotation={[-1.453, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Plane006_0.geometry}
        material={materials["toiture-tole.001"]}
        position={[16.693, 3.758, -5.121]}
        rotation={[-1.712, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Cube005_0.geometry}
        material={materials.Material}
        position={[2.256, 3.1, 0.099]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.Cube006_0.geometry}
        material={materials["poutre-toit.003"]}
        position={[2.256, 3.132, -10.01]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <mesh
        geometry={nodes.TexturesCom_DoorsRollup0044_M_0.geometry}
        material={materials.TexturesCom_DoorsRollup0044_M}
        position={[16.878, -1.277, -2.618]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={2.392}
      />
      <mesh
        geometry={nodes.TexturesCom_DoorsWoodBarn0017_M_0.geometry}
        material={materials.TexturesCom_DoorsWoodBarn0017_M}
        position={[16.878, -1.428, -7.564]}
        rotation={[0, Math.PI / 2, 0]}
        scale={3.51}
        info={{
          titulo: "Puerta de madera",
          texto: "Capa de puerta de madera.",
        }}
      />
      <MallaInteractiva
        geometry={nodes.Plane008_0.geometry}
        material={materials.chaise}
        position={[3.842, -2.444, -5.926]}
        rotation={[-Math.PI / 2, 0, 0.925]}
        scale={0.178}
        info={{
          titulo: "Chaise",
          texto: "Capa de chaise.",
        }}
      />
      <mesh
        geometry={nodes.BezierCurve006_0.geometry}
        material={materials.cable}
        position={[-2.824, 2.607, -8.809]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.51}
      />
      <MallaInteractiva
        geometry={nodes.Circle001_0.geometry}
        material={materials.lampe}
        position={[0, 0.728, -2.348]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.313}
        info={{
          titulo: "Lámpara",
          texto: "Capa de lámpara.",
        }}
      />
      <mesh
        geometry={nodes.Circle001_1.geometry}
        material={materials["lampe-interieure"]}
        position={[0, 0.728, -2.348]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.313}
      />
      <mesh geometry={nodes.pandagun_1280_0.geometry} material={materials.pandagun_1280} position={[-4.332, -1.868, 0.129]} scale={2.254} />
      <mesh
        geometry={nodes.DM_Watch_Your_Step_graffiti_0.geometry}
        material={materials.DM_Watch_Your_Step_graffiti}
        position={[-4.166, 0.274, 0.131]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.813}
      />
      <mesh
        geometry={nodes.Cube009_0.geometry}
        material={materials.palette}
        position={[0.23, -2.845, -7.347]}
        rotation={[-Math.PI / 2, 0, -2.338]}
        scale={0.43}
      />
      <mesh
        geometry={nodes.Cube010_0.geometry}
        material={materials["palette.001"]}
        position={[-4.25, -2.928, -7.423]}
        rotation={[-Math.PI / 2, 0, -1.734]}
        scale={0.43}
      />
      <mesh
        geometry={nodes.TexturesCom_CardboardPlain0019_2_alphamasked_S049_0.geometry}
        material={materials.TexturesCom_CardboardPlain0019_2_alphamasked_S}
        position={[-1.66, -2.933, -5.555]}
        rotation={[-1.572, 0.015, 0.587]}
        scale={0.409}
      />
      <mesh
        geometry={nodes.TexturesCom_CardboardPlain0019_2_alphamasked_S049_1.geometry}
        material={materials.TexturesCom_CardboardPlain0022_2_alphamasked_S}
        position={[-1.66, -2.933, -5.555]}
        rotation={[-1.572, 0.015, 0.587]}
        scale={0.409}
      />
      <mesh
        geometry={nodes.TexturesCom_CardboardPlain0019_2_alphamasked_S049_2.geometry}
        material={materials.TexturesCom_CardboardPlain0026_2_alphamasked_S}
        position={[-1.66, -2.933, -5.555]}
        rotation={[-1.572, 0.015, 0.587]}
        scale={0.409}
      />
      <mesh
        geometry={nodes.Icosphere1295_0.geometry}
        material={materials.gravas}
        position={[-4.014, -2.933, -4.881]}
        rotation={[-1.584, 0.006, 0.69]}
        scale={0.035}
      />
    </group>
  );
}

useGLTF.preload("./models/abandoned_warehouse_-_interior_scene-transformed.glb");
