/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/original/hintze_hall.glb --transform 
Files: public/original/hintze_hall.glb [156.31MB] > C:\Users\jova1\Documents\ar-arch-edu\hintze_hall-transformed.glb [10.73MB] (93%)
Author: artfletch (https://sketchfab.com/artfletch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hintze-hall-45f5e56887f44075bbf283977c99541f
Title: Hintze Hall
*/

import { useGLTF } from "@react-three/drei";
import { MallaInteractiva } from "./MallaInteractiva";

export function Museo(props) {
  const { nodes, materials } = useGLTF("./models/hintze_hall-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <MallaInteractiva
        geometry={nodes.Object_2.geometry}
        material={materials.NHMHintzeHall02_Model_9_u2_v1}
        rotation={[-Math.PI, 0, 0]}
        scale={1.429}
        info={{
          titulo: "Museo",
          texto: "Museo de arte.",
        }}
      />
      <mesh geometry={nodes.Object_3.geometry} material={materials.NHMHintzeHall02_Model_9_u1_v1} rotation={[-Math.PI, 0, 0]} scale={1.429} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.lambert4SG} rotation={[-Math.PI, 0, 0]} scale={1.429} />
    </group>
  );
}

useGLTF.preload("./models/hintze_hall-transformed.glb");
