/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/realistic_broken_pillars.glb --transform 
Files: public/realistic_broken_pillars.glb [8.2MB] > C:\Users\jova1\Documents\ar-arch-edu\realistic_broken_pillars-transformed.glb [900.02KB] (89%)
Author: abhayexe (https://sketchfab.com/abhayexe)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/realistic-broken-pillars-b0d2bd3097e94444b07cc53c3fc5c355
Title: Realistic Broken Pillars
*/

import { useGLTF, Html } from "@react-three/drei";
import { MallaInteractiva } from "./MallaInteractiva";

export function RealisticBrokenPillars(props) {
  const { nodes, materials } = useGLTF("./models/realistic_broken_pillars-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <MallaInteractiva
        geometry={nodes.Object_4.geometry}
        material={materials["Material.004"]}
        position={[0, 0, 0]}
        info={{
          titulo: "Columna",
          texto: "Soporta el peso estructural.",
        }}
      />
    </group>
  );
}

useGLTF.preload("./models/realistic_broken_pillars-transformed.glb");
